# Generated by Django 3.1.7 on 2021-05-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210511_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemilarRanobe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('ranobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ranobe')),
            ],
        ),
        migrations.CreateModel(
            name='SemilarManga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manga')),
            ],
        ),
    ]
