# Generated by Django 3.1.7 on 2021-05-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_semilarmanga_semilarranobe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='authors',
            field=models.ManyToManyField(to='main.Author'),
        ),
        migrations.AddField(
            model_name='ranobe',
            name='authors',
            field=models.ManyToManyField(to='main.Author'),
        ),
    ]
