# Generated by Django 3.1.7 on 2021-05-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210513_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='authors',
            field=models.ManyToManyField(null=True, to='main.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='ranobe',
            name='authors',
            field=models.ManyToManyField(null=True, to='main.Author', verbose_name='Автор'),
        ),
    ]
