# Generated by Django 3.1.7 on 2021-05-14 11:04

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210513_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='journal_photos', validators=[utils.validators.validate_size, utils.validators.validate_extension]),
        ),
        migrations.AddField(
            model_name='ranobe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='journal_photos', validators=[utils.validators.validate_size, utils.validators.validate_extension]),
        ),
    ]
