# Generated by Django 3.1.7 on 2021-05-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210514_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='price',
            field=models.IntegerField(default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ranobe',
            name='price',
            field=models.IntegerField(default=0, null=True, verbose_name='Цена'),
        ),
    ]
