# Generated by Django 3.1.7 on 2022-05-04 15:47

import datetime
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210515_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price', models.IntegerField(default=0, null=True, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('genre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Жанр')),
                ('publication_date', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos', validators=[utils.validators.validate_size, utils.validators.validate_extension])),
                ('color_type', models.CharField(choices=[('Черно-белый', 'Черно-белый'), ('Цветной', 'Цветной')], default='Черно-белый', max_length=20, verbose_name='Цвет манги')),
                ('release_type', models.CharField(choices=[('Еженедельник', 'Еженедельник'), ('Ежемесячник', 'Ежемесячник')], default='Еженедельник', max_length=20, verbose_name='Тип издания')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книга',
            },
        ),
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price', models.IntegerField(default=0, null=True, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('genre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Жанр')),
                ('publication_date', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos', validators=[utils.validators.validate_size, utils.validators.validate_extension])),
                ('type', models.CharField(choices=[('Для детей', 'Для детей'), ('18+', '18+'), ('16+', '16+')], default='Для детей', max_length=20, verbose_name='Тип')),
                ('num_pages', models.IntegerField(default=0, verbose_name='Количество страниц')),
            ],
            options={
                'verbose_name': 'Комикс',
                'verbose_name_plural': 'Комикс',
            },
        ),
        migrations.CreateModel(
            name='SimilarBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarComics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='manga',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='ranobe',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='ranobe',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='semilarmanga',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='semilarranobe',
            name='ranobe',
        ),
    ]
