# Generated by Django 3.1.7 on 2022-05-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0002_auto_20220504_2147'),
        ('main', '0016_auto_20220504_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manga',
        ),
        migrations.DeleteModel(
            name='Ranobe',
        ),
        migrations.DeleteModel(
            name='SemilarManga',
        ),
        migrations.DeleteModel(
            name='SemilarRanobe',
        ),
        migrations.AddField(
            model_name='similarcomics',
            name='comics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comics'),
        ),
        migrations.AddField(
            model_name='similarbook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.book'),
        ),
        migrations.AddField(
            model_name='comics',
            name='authors',
            field=models.ManyToManyField(to='main.Author'),
        ),
        migrations.AddField(
            model_name='comics',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.publisher', verbose_name='Издатель'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='main.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.publisher', verbose_name='Издатель'),
        ),
    ]
