# Generated by Django 3.1.7 on 2022-05-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220504_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='color_type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='release_type',
        ),
        migrations.RemoveField(
            model_name='comics',
            name='num_pages',
        ),
        migrations.RemoveField(
            model_name='comics',
            name='type',
        ),
        migrations.AddField(
            model_name='book',
            name='num_pages',
            field=models.IntegerField(default=0, verbose_name='Количество страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Для детей', 'Для детей'), ('18+', '18+'), ('16+', '16+')], default='Для детей', max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='comics',
            name='color_type',
            field=models.CharField(choices=[('Черно-белый', 'Черно-белый'), ('Цветной', 'Цветной')], default='Черно-белый', max_length=20, verbose_name='Цвет манги'),
        ),
        migrations.AddField(
            model_name='comics',
            name='release_type',
            field=models.CharField(choices=[('Еженедельник', 'Еженедельник'), ('Ежемесячник', 'Ежемесячник')], default='Еженедельник', max_length=20, verbose_name='Тип издания'),
        ),
    ]
