# Generated by Django 3.1.7 on 2022-05-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220505_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='color_type',
            field=models.CharField(choices=[('Черно-белый', 'Черно-белый'), ('Цветной', 'Цветной')], default='Черно-белый', max_length=20, verbose_name='Цвет Комикса'),
        ),
    ]
