# Generated by Django 3.1.7 on 2021-05-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('0/5 - оценок пока нет', '0/5 - оценок пока нет'), ('1/5', '1/5'), ('2/5', '2/5'), ('3/5', '3/5'), ('4/5', '4/5'), ('5/5', '5/5')], default='0/5 - оценок пока нет', max_length=30, verbose_name='Рейтинг товара'),
        ),
    ]
