# Generated by Django 3.1.7 on 2021-05-14 13:43

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertising_photos', validators=[utils.validators.validate_size, utils.validators.validate_extension])),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
            },
        ),
    ]
